title: <p align="center"> Augusto Dos Santos </p>

logo: "/images/picture.png?raw=true" 
logo_style: "display: block; margin: 0 auto;" 

description:
  <p align="center">
  <a href="linkedin.com/in/augusto-dos-santos-a226622b6">LinkedIn</a> |
  <a href="https://github.com/augustosz">GitHub</a>
  </p>
  
  <p>
  -ANALISTA DE SISTEMAS INFORM√ÅTICOS- 
  <br><br>
  üëã Hola, soy Augusto y me especializo como desarrollador Back-End con experiencia practica en Python, Node.js y bases de datos SQL/NoSQL, especializado en la construcci√≥n de APIs REST y optimizaci√≥n de consultas.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
